In [ ]:
a = 5 # this is a scalar

print(a)

In [ ]:
b = [1,2,3]

print(b)

In [10]:
c = [[1,2,3],[4,5,6]] # list, mathematical ops cannot be done
print(c)

[[1, 2, 3], [4, 5, 6]]


In [11]:
d = [4,5,6]    
print(b+d)        # concatenate

[1, 2, 3, 4, 5, 6]


In [13]:
c[0][1]     # accessing list elements

2

In [14]:
!pip install numpy        # allows jupyter to execute command in terminal

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 4.7 MB/s eta 0:00:00m eta 0:00:010:01:01


In [16]:
import numpy as np

In [20]:
z = np.array([[1],[2],[3]])
z.shape

(3, 1)

In [22]:
y = np.array([[1,2,3]])
y.shape

(1, 3)

In [23]:
print(z*y)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [24]:
np.arange(1,10)            # start and end not inclusive of end

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2)         # start stop step

array([1, 3, 5, 7, 9])

In [29]:
p = np.arange(1,100)
p[50:55]

array([51, 52, 53, 54, 55])

In [38]:
p = p.reshape(11,9)
p

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
p.shape

(11, 9)

In [40]:
p[4:7,3:6]

array([[40, 41, 42],
       [49, 50, 51],
       [58, 59, 60]])

In [46]:
y.tolist()
z.tolist()

[[1], [2], [3]]

In [48]:
np.array(a)

array(5)